In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("/kaggle/input/datasets/divjotbedi/customer-dataset-with-education-age-gender/customer.csv")

In [3]:
df.head()

   age  gender purchased     review education
0   58    Male       Yes       Good        UG
1   32    Male       Yes       Poor    School
2   45    Male       Yes       Poor        UG
3   32    Male       Yes  Excellent        UG
4   46  Female       Yes    Average    School

In [4]:
df=df.iloc[:,2:]

In [8]:
df.sample(10)

    purchased     review education
394        No       Good    School
65        Yes       Good    School
203        No       Good        PG
144       Yes    Average        UG
466       Yes  Excellent    School
30        Yes  Excellent        UG
287       Yes       Good    School
405       Yes       Poor        PG
69        Yes       Poor        UG
261       Yes  Excellent        UG

In [9]:
from sklearn.model_selection import train_test_split

In [12]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],
                                              df.iloc[:,0],
                                              test_size=0.2,
                                              random_state=42)

In [13]:
X_train.head()

        review education
249  Excellent        PG
433    Average        PG
19   Excellent    School
322  Excellent        PG
332       Good        UG

In [14]:
X_test.head()

        review education
361    Average        UG
73        Good    School
374  Excellent    School
155       Good    School
104       Poor    School

In [15]:
y_train.head()

249     No
433    Yes
19      No
322    Yes
332    Yes
Name: purchased, dtype: object

In [16]:
y_test.head()

361     No
73     Yes
374    Yes
155     No
104     No
Name: purchased, dtype: object

In [19]:
from sklearn.preprocessing import OrdinalEncoder

In [21]:
from sklearn.preprocessing import LabelEncoder

In [25]:
Oe=OrdinalEncoder(categories=[['Poor','Average','Good','Excellent'],['School','UG','PG']])

In [26]:
Oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good', 'Excellent'],
                           ['School', 'UG', 'PG']])

In [27]:
X_train=Oe.transform(X_train)
X_test=Oe.transform(X_test)

In [29]:
X_train

array([[3., 2.],
       [1., 2.],
       [3., 0.],
       [3., 2.],
       [2., 1.],
       [1., 0.],
       [1., 0.],
       [3., 2.],
       [2., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [3., 1.],
       [2., 1.],
       [2., 2.],
       [0., 0.],
       [0., 1.],
       [3., 2.],
       [0., 2.],
       [2., 0.],
       [3., 0.],
       [2., 1.],
       [0., 0.],
       [3., 2.],
       [1., 2.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 1.],
       [3., 0.],
       [1., 2.],
       [0., 0.],
       [3., 0.],
       [1., 2.],
       [2., 2.],
       [1., 2.],
       [2., 1.],
       [1., 0.],
       [2., 2.],
       [0., 0.],
       [2., 0.],
       [2., 2.],
       [1., 1.],
       [1., 0.],
       [3., 2.],
       [0., 0.],
       [0., 0.],
       [3., 1.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [0., 2.],
       [3., 2.],
       [3., 1.],
       [1., 1.],
       [3., 1.],
       [3., 0.],
       [0., 2.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [3., 2.],
       [1., 1.],
       [3., 2.],
       [3., 1.],
       [0., 0.],
       [2., 1.],
       [0., 0.],
       [3., 1.],
       [0., 1.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [0., 1.],
       [3., 2.],
       [0., 1.],
       [3., 0.],
       [1., 1.],
       [1., 2.],
       [2., 2.],
       [3., 0.],
       [1., 1.],
       [3., 0.],
       [0., 1.],
       [2., 2.],
       [3., 0.],
       [0., 2.],
       [2., 1.],
       [2., 0.],
       [0., 0.],
       [2., 0.],
       [0., 2.],
       [3., 0.],
       [0., 0.],
       [3., 1.],
       [2., 1.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [3., 0.],
       [2., 2.],
       [0., 1.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [3., 2.],
       [1., 1.],
       [3., 2.],
       [1., 0.],
       [3., 2.],
       [1., 0.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [0., 1.],
       [3., 0.],
       [2., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [0., 1.],
       [2., 1.],
       [0., 1.],
       [3., 0.],
       [3., 1.],
       [1., 1.],
       [3., 0.],
       [0., 0.],
       [1., 2.],
       [2., 2.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [3., 2.],
       [2., 1.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [0., 1.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [2., 0.],
       [3., 0.],
       [0., 1.],
       [2., 0.],
       [3., 2.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [1., 0.],
       [1., 0.],
       [2., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [2., 0.],
       [0., 1.],
       [1., 2.],
       [3., 0.],
       [0., 0.],
       [1., 0.],
       [2., 1.],
       [3., 2.],
       [0., 0.],
       [3., 0.],
       [3., 1.],
       [3., 0.],
       [2., 2.],
       [0., 0.],
       [0., 0.],
       [3., 0.],
       [2., 2.],
       [3., 0.],
       [3., 0.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [0., 0.],
       [0., 2.],
       [3., 2.],
       [0., 0.],
       [0., 0.],
       [2., 0.],
       [3., 2.],
       [3., 0.],
       [3., 0.],
       [1., 2.],
       [1., 0.],
       [0., 2.],
       [3., 1.],
       [2., 0.],
       [1., 0.],
       [2., 1.],
       [1., 0.],
       [2., 2.],
       [1., 2.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [0., 0.],
       [2., 0.],
       [0., 0.],
       [3., 1.],
       [1., 1.],
       [1., 0.],
       [3., 1.],
       [2., 0.],
       [1., 0.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 1.],
       [3., 0.],
       [2., 2.],
       [3., 1.],
       [1., 1.],
       [2., 0.],
       [1., 0.],
       [1., 2.],
       [3., 0.],
       [3., 0.],
       [3., 0.],
       [0., 1.],
       [2., 2.],
       [2., 1.],
       [3., 1.],
       [0., 2.],
       [3., 2.],
       [2., 1.],
       [2., 0.],
       [2., 1.],
       [3., 0.],
       [0., 0.],
       [3., 2.],
       [1., 2.],
       [1., 2.],
       [3., 1.],
       [3., 2.],
       [3., 0.],
       [1., 2.],
       [2., 2.],
       [0., 1.],
       [3., 2.],
       [3., 2.],
       [1., 0.],
       [1., 1.],
       [3., 2.],
       [1., 2.],
       [1., 2.],
       [1., 0.],
       [2., 0.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [1., 2.],
       [3., 2.],
       [1., 0.],
       [2., 2.],
       [1., 2.],
       [3., 1.],
       [3., 1.],
       [2., 1.],
       [1., 2.],
       [2., 0.],
       [2., 2.],
       [3., 1.],
       [2., 1.],
       [3., 1.],
       [1., 0.],
       [2., 0.],
       [1., 2.],
       [2., 1.],
       [1., 0.],
       [3., 1.],
       [0., 2.],
       [1., 0.],
       [2., 0.],
       [0., 2.],
       [3., 2.],
       [1., 0.],
       [1., 1.],
       [2., 0.],
       [1., 2.],
       [3., 1.],
       [2., 2.],
       [3., 2.],
       [2., 2.],
       [0., 0.],
       [2., 2.],
       [1., 0.],
       [3., 1.],
       [0., 2.],
       [3., 2.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 2.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [3., 1.],
       [1., 1.],
       [0., 2.],
       [2., 0.],
       [1., 2.],
       [2., 0.],
       [2., 1.],
       [2., 2.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [2., 0.],
       [3., 2.],
       [3., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [3., 2.],
       [2., 1.],
       [0., 2.],
       [3., 0.],
       [2., 2.],
       [0., 1.],
       [3., 0.],
       [1., 0.],
       [2., 1.],
       [1., 2.],
       [3., 1.],
       [0., 2.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 2.],
       [1., 0.],
       [0., 0.],
       [3., 1.],
       [3., 2.],
       [3., 1.],
       [1., 0.],
       [1., 1.],
       [3., 0.],
       [2., 1.],
       [3., 1.],
       [2., 0.],
       [1., 0.],
       [3., 2.],
       [3., 2.],
       [2., 1.],
       [0., 1.],
       [2., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [3., 0.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [1., 2.],
       [0., 1.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [3., 2.],
       [3., 1.],
       [3., 1.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [3., 2.],
       [2., 1.],
       [3., 1.],
       [2., 0.],
       [3., 0.],
       [1., 2.],
       [0., 0.],
       [1., 0.],
       [3., 1.],
       [1., 1.],
       [1., 1.],
       [2., 2.],
       [3., 2.],
       [2., 2.],
       [3., 2.]])

In [30]:
Le=LabelEncoder()

In [31]:
Le.fit(y_train)

LabelEncoder()

In [33]:
Le.classes_

array(['No', 'Yes'], dtype=object)

In [35]:
y_train=Le.transform(y_train)
y_test=Le.transform(y_test)

In [36]:
y_train

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0])