In [27]:
import pandas as pd
import numpy as np

In [9]:
df=pd.read_csv("/kaggle/input/datasets/divjotbedi/indian-cars-data/cars.csv")

In [10]:
df.head()

    brand  km_driven    fuel         owner  selling_price
0    Ford     180638  Diesel  Fourth Owner         129000
1   Skoda     105863     CNG   First Owner         486000
2  Maruti      19829     CNG  Second Owner         226000
3    Tata      73088  Petrol   First Owner         344000
4     Kia     158230  Petrol   First Owner         491000

In [11]:
df['brand'].value_counts()

brand
Skoda         64
Hyundai       59
Mahindra      56
Tata          55
Toyota        54
Ford          52
Maruti        49
Volkswagen    45
Kia           36
Honda         30
Name: count, dtype: int64

In [12]:
df['fuel'].value_counts()

fuel
CNG       178
Diesel    168
Petrol    154
Name: count, dtype: int64

In [13]:
df['owner'].value_counts()

owner
Second Owner    142
First Owner     127
Third Owner     117
Fourth Owner    114
Name: count, dtype: int64

# *1. OneHotEncoding Using Pandas*

In [62]:
pd.get_dummies(df,columns=['fuel','owner'],dtype=int)

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_Petrol,owner_First Owner,owner_Fourth Owner,owner_Second Owner,owner_Third Owner
0,Ford,180638,129000,0,1,0,0,1,0,0
1,Skoda,105863,486000,1,0,0,1,0,0,0
2,Maruti,19829,226000,1,0,0,0,0,1,0
3,Tata,73088,344000,0,0,1,1,0,0,0
4,Kia,158230,491000,0,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...
495,Skoda,197982,432000,0,0,1,1,0,0,0
496,Maruti,131856,273000,0,0,1,1,0,0,0
497,Volkswagen,38846,314000,1,0,0,0,0,0,1
498,Skoda,151976,383000,0,0,1,0,0,1,0
499,Hyundai,185315,331000,0,1,0,0,0,1,0

# *2. K-1 OneHotEncoding Using Pandas***

In [14]:
pd.get_dummies(df,columns=['fuel','owner'],dtype=int,drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_Petrol,owner_Fourth Owner,owner_Second Owner,owner_Third Owner
0,Ford,180638,129000,1,0,1,0,0
1,Skoda,105863,486000,0,0,0,0,0
2,Maruti,19829,226000,0,0,0,1,0
3,Tata,73088,344000,0,1,0,0,0
4,Kia,158230,491000,0,1,0,0,0
...,...,...,...,...,...,...,...,...
495,Skoda,197982,432000,0,1,0,0,0
496,Maruti,131856,273000,0,1,0,0,0
497,Volkswagen,38846,314000,0,0,0,0,1
498,Skoda,151976,383000,0,1,0,1,0
499,Hyundai,185315,331000,1,0,0,1,0

In [15]:
df.head()

    brand  km_driven    fuel         owner  selling_price
0    Ford     180638  Diesel  Fourth Owner         129000
1   Skoda     105863     CNG   First Owner         486000
2  Maruti      19829     CNG  Second Owner         226000
3    Tata      73088  Petrol   First Owner         344000
4     Kia     158230  Petrol   First Owner         491000

# *3. OneHotEncoding Using Sklearn*

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.3,random_state=42)

In [39]:
X_train.head()

        brand  km_driven    fuel         owner
5     Hyundai     161284     CNG   First Owner
116       Kia      95494  Diesel  Fourth Owner
45     Toyota      53789     CNG   Third Owner
16      Skoda      53243  Diesel  Fourth Owner
462  Mahindra      71310  Petrol   Third Owner

In [20]:
X_test.head()

          brand  km_driven    fuel         owner
361    Mahindra      48342     CNG  Second Owner
73   Volkswagen     191595     CNG  Second Owner
374      Toyota     191611  Diesel  Fourth Owner
155         Kia      41389     CNG  Fourth Owner
104        Tata      44031  Petrol   First Owner

In [21]:
y_train

5      370000
116    284000
45     377000
16     261000
462    263000
        ...
106    131000
270    228000
348    373000
435    320000
102    295000
Name: selling_price, Length: 350, dtype: int64

In [22]:
y_test

361    333000
73     367000
374    261000
155    254000
104    348000
        ...
266    243000
23     272000
222    389000
261    282000
426    426000
Name: selling_price, Length: 150, dtype: int64

In [24]:
from sklearn.preprocessing import OneHotEncoder

In [29]:
OHe=OneHotEncoder(sparse_output=False,drop='first',dtype=np.int32)

In [37]:
X_train_new=OHe.fit_transform(X_train[['fuel','owner']])
X_test_new=OHe.fit_transform(X_test[['fuel','owner']])

In [41]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Hyundai', 161284, 0, ..., 0, 0, 0],
       ['Kia', 95494, 1, ..., 1, 0, 0],
       ['Toyota', 53789, 0, ..., 0, 0, 1],
       ...,
       ['Volkswagen', 181570, 0, ..., 0, 1, 0],
       ['Mahindra', 59584, 0, ..., 0, 1, 0],
       ['Kia', 190287, 0, ..., 0, 0, 1]], dtype=object)

# *4. OneHotEncoding With top categories*

In [47]:
counts=df['brand'].value_counts()

In [48]:
df['brand'].nunique()

10

In [56]:
threshold=40
repl=counts[counts<=threshold].index

In [60]:
pd.get_dummies(df['brand'].replace(repl,'Other'),dtype=int).sample(10)

     Ford  Hyundai  Mahindra  Maruti  Other  Skoda  Tata  Toyota  Volkswagen
81      0        0         0       0      1      0     0       0           0
209     0        0         0       0      0      0     1       0           0
440     1        0         0       0      0      0     0       0           0
423     0        0         0       0      0      0     0       1           0
242     0        0         0       0      1      0     0       0           0
273     0        0         0       0      0      0     0       1           0
279     0        0         0       0      1      0     0       0           0
328     0        0         1       0      0      0     0       0           0
494     0        0         1       0      0      0     0       0           0
306     0        0         0       1      0      0     0       0           0

In [61]:
df.head()

    brand  km_driven    fuel         owner  selling_price
0    Ford     180638  Diesel  Fourth Owner         129000
1   Skoda     105863     CNG   First Owner         486000
2  Maruti      19829     CNG  Second Owner         226000
3    Tata      73088  Petrol   First Owner         344000
4     Kia     158230  Petrol   First Owner         491000